### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#12]
Add logging to:
- Making new files
- config changes
- upload / download

**Comment by JoeZiminski** [comment]
Raises some interesting questions as to where logs are stored. This could be a) in the datashuttle config folder b) in the project folder itself, and also how to handle different logs across computers. I think to start, the logs can be stored on the local PC in the datashuttle config folder (especially now it is easy to find), with no attempt at 'merging' logs across computers. Maybe in future we can push all local logs to the remote?

**Comment by adamltyson** [comment]
I was thinking that the logs should be associated with the project folder itself, so that it's easy to see what was synced and when (especially if something went wrong).

Perhaps every project should have a `datashuttle` directory (possibly hidden) to store lots of lots from every sync, and potentially other things like copies of config files?
