### ISSUE TITLE
[TUI] General Meeting Notes TUI

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#184]
# TUI Overview Meeting 29/09/2023

## 
![Screenshot 2023-09-29 at 15 19 54](https://github.com/neuroinformatics-unit/datashuttle/assets/55797454/482c1c75-493b-4d41-b6cd-b08a52f90588)

![Screenshot 2023-09-29 at 15 21 52](https://github.com/neuroinformatics-unit/datashuttle/assets/55797454/4aac7a03-1163-4779-9a8e-1c26cd118c58)

![Screenshot 2023-09-29 at 15 22 07](https://github.com/neuroinformatics-unit/datashuttle/assets/55797454/df0c7acf-330a-478b-8546-3c57e9394ab0)

# Feature Ideas:

- Have an easy way to switch between projects.
- A way to fill the subject / session 'Input' by double clicking / right-click and select on a window a subject / session in the 'Directory Tree'. 
- Have a way of easily inputting the tags into the Input fields (e.g. @DATE@). 
- A tooltip for what will be created when making folders i.e. indicate exactly the path where new folders will be created.
- Look up best-practices in GUI design e.g. if auto-filling the subject / session field, should this be double click vs. pop up menu? What kind of widget is most associated with creation e.g. folder creation.
- Functionality for deleting folders?

## Data transfer

- Also display the Directory Tree for the central storage file tree (this requires - shh to server - populate file tree)
- Indicate the direction of file transfer with arrows left - right that pass between the two directory tree widgets.
- Previewing data transfer - the colour of folders in the directory tree could reflect what will happen on file transfer (with current settings). 
- Select files and folders to transfer by clicking on the file tree.

**Comment by b-peri** [comment]
On 13/10/2023, @JoeZiminski and I had a brief meeting to discuss current progress and potential next steps for the TUI project.

### **Current Features**

The following features are either already implemented in the GUI, or will be completed very soon:
- A main interface screen with switchable content tabs
- A "Create" tab populated with the following widgets:
     - A functioning ```DirectoryTree``` widget which can be easily set to any given root directory
     - Subject and session input fields which can be automatically populated by double-clicking any directories on the DirectoryTree starting with "sub-" or "ses-" respectively
     - Functioning Datatype selection which 
     - A "Make Folders" button which  

### **Next Steps**

Once the above features have been successfully implemented, @JoeZiminski and I decided that the logical next step would be to start working on the screens for project selection and configuration. I proposed the following basic design:

## 1. Project Selection Splashscreen

![image](https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/830032c1-202a-4952-9b38-3c229977d4eb)

For the TUI´s initial project selection screen, we settling on a retro video game-inspired "Save Select" window in which individual projects are represented by ```Button``` widgets containing project name, as well as some relevant details about the project itself, e.g. date last edited, datatypes, number of subjects, etc. (the specifics here are to be discussed). These widgets can be set to populate the window dynamically based on the number of projects detected on the local system (e.g. using the new ```get_existing_project_paths_and_names()``` function added w/ PR #202) to minimize clutter. If there are no existing projects detected, only the _New Project_ button will be shown. Clicking on an existing project will bring the user to a separate Textual Screen (see: https://textual.textualize.io/guide/screens/) containing the ```TabbedContent``` viewer (above) preconfigured to interact with the selected project. Clicking on the _New Project_ button will bring the user to the following screen, where project details (essentially make_config_file) can be configured:

## 2. New Project Configuration

![image](https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/42e7ace4-0a65-4ed1-bf44-f730a5882d2f)

For now, Joe and I agreed that this can be a simple form containing a bunch of ```Input``` widgets for manual textual input, and where appropriate ```Select``` and/or ```Checkbox``` widgets. This screen will contain a single "Create Project" button at the bottom capable of calling ```project.make_config_file``` directly.

## 3. Further Additions to TabbedContent

![image](https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/d8d409b8-4961-4ea9-9ae3-d9d25f224286)

# Create Tab

We also discussed some more detailed next steps for the create tab. I proposed that, in the interest of keeping the TUI as clean, minimal, and user-friendly as possible, we attempt to have the majority of our validation processes running under the hood (rather than being activated explicitly with buttons). It is e.g. possible to implement continuous validation for the contents of ```Input``` widgets that runs every time the contents of the box are changed (https://textual.textualize.io/widgets/input/#validating-input). The validation status can be set to assign a CSS class to the Input widget, which can be used to style the widget differently based on said status. For now, I proposed that we have the box be grey before the user has interacted with it, and then either red (invalid input) or green (valid input) once anything has been changed.

We agreed that a two-step validation process would be the cleanest, with "quick" checks (for e.g. NeuroBlueprint compliance) running as continuous validators on the Input widgets themselves, and more heavy checks running only once the user has clicked the "Make Folders" button. Issue-specific error messages can then be passed to the user by either composing a textbox on the screen itself (as shown above) or with a Pop-Up overlay.

# Other

Beyond the create and transfer tabs discussed previously, we can consider adding a Config/Settings tab in which major project settings can be edited, as well as a Log tab containing a record of all actions performed on the current project. We should also implement a "Back" button (shown in the above image as "Projects") via which the user can return to the intial project selection splashscreen.

**Comment by JoeZiminski** [comment]
As a rough timeline, we will:
1) Implement splash screen 
2) implement config setup
3) implement creation page in full

then get user feedback + write tests. After this we can:

4) work on data transfer page.

**Comment by b-peri** [comment]
On 26/10/23, @JoeZiminski and I met again to discuss current progress and draft a rough plan for how we will move forward with the TUI.

# Status Report: Current Features & Progress

The TUI has been coming along steadily, and is now capable of executing many of the core functions of DataShuttle. At the time of writing, we have implemented the following features:

1. A main menu, from which the user can navigate to the 'Project Selection' and 'New Project Configuration' screens (described below). The menu also features 'Settings' and 'Get Help' buttons, which have not yet been implemented.
2. A project selection screen (`ProjectSelector`), which automatically detects all DataShuttle projects configured on the local filesystem and uses this to dynamically render clickable `Button` widgets. Clicking on any project title loads the project into DataShuttle and instantiates a `TabScreen` object preconfigured for said project.
3. A New Project Configuration screen (`NewProjectScreen`), from which the user can provide all inputs necessary to run `datashuttle.make_config_file`. 
4. Once a DataShuttle project has been selected or configured, the user is brought to the `TabScreen`, where they can begin interacting with their project. Currently, this screen contains:
     - A bare-bones `Create` tab, as described in detail in my previous post on this issue.
     - A `Config` tab, from which the user can edit major project configurations (e.g. local path, connection method, etc.)

# What's Next?

## 1. Refactoring

A current bottleneck in our development pipeline is that all of the TUI logic is contained in a single (now rather unwieldy) script. To improve code legibility and make it easier to work on the code simultaneously, I will start by performing a major refactoring of `app.py`. While the specifics of what-will-go-where is still subject to change, the rough idea is currently as follows:

<img width="672" alt="image" src="https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/d77da148-ab79-4b5b-aefd-945cb5c7c5b2">

- `tui_app.py`: The main Textual app for the TUI (`TuiApp`), and the script that the user will call from the terminal when they want to run the TUI from terminal (for now).
- `project_config.py`: `ConfigsContent`, `NewProjectScreen`, and associated objects involving configuration of a new project or updating configs for a pre-existing project.
- `tui_logic.py`: TUI-specific functions and logic
- `custom_widgets.py`: Custom widgets and **multi-use** modal windows built for the TUI (e.g. `DatatypeCheckboxes` or `ErrorScreen`, but not `ShowConfigsDialog`)
- TabScreen Tabs will be subdivided into:
     - `main_tab.py`: Containing the main `TabScreen` and associated (non-tab-specific) logic
     - `create_tab.py`: Create tab and associated logic
     - `transfer_tab.py`: Transfer tab and associated logic
     - And so on...
     - **NOTE:** The configs tab will likely not require a separate script from `project_config.py` 

I'm still very much a novice to software development (and even just Python), so please feel free to let me know if you feel there's anything I can improve here!

## 2. Transfer Tab

Once refactoring has been completed, I will get started on implementing a basic form of the transfer tab. In the interest of minimizing clutter and preserving some horizontal space, I'm hoping to represent the transfer status of local project files within a _single_ filetree (rather than the two-tree model we discussed initially). Thus, instead of showing both local and remote trees simultaneous, I am hoping to use dynamic tcss classing to indicate to the user what the transfer status of individual project files is. See here a mock image with some further details:

<img width="582" alt="image" src="https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/778c0aeb-401a-476f-825a-45b8fc222583">


## 3. Additions to Create Tab

In parallel, Joe will start implementing some of the fancier stuff on the `Create` tab, including input validation and .... options (See above).

# Other Additions?

After the above refactoring, the TUI script will be fairly modular, and it should in theory be possible to work on separate modules in parallel without creating too much of a merging nightmare (hopefully). Joe and I will be continuing to roll out features over the next few months, but if you have a particular idea or are otherwise keen to help out, please do feel free to jump in and pick up an issue (or make a new one yourself) at any point along the way!
